name: Secrets audit

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: gitleaks-action
        uses: aslafy-z/gitleaks-action@912885d
